# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-11 16:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=200)),
                ('grade_range', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='AwardWinner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('award', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='judge_app.Award')),
            ],
        ),
        migrations.CreateModel(
            name='JudgingResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judge_id', models.CharField(max_length=255)),
                ('score', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('response_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('school', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=50)),
                ('grade_level', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=10)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='judge_app.Project')),
            ],
        ),
        migrations.AddField(
            model_name='judgingresult',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='judge_app.Project'),
        ),
        migrations.AddField(
            model_name='awardwinner',
            name='project',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='judge_app.Project'),
        ),
        migrations.AddField(
            model_name='award',
            name='judge_results',
            field=models.ManyToManyField(blank=True, related_name='judge_results', to='judge_app.JudgingResult'),
        ),
        migrations.AddField(
            model_name='award',
            name='winners',
            field=models.ManyToManyField(blank=True, related_name='winners', to='judge_app.Project'),
        ),
    ]
