# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-16 15:29
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Award',
            fields=[
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='code', unique=True)),
                ('code', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=200)),
                ('grade_range', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AwardWinner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('final_score', models.DecimalField(blank=True, decimal_places=7, max_digits=15, null=True)),
                ('award', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='judge_app.Award')),
            ],
        ),
        migrations.CreateModel(
            name='JudgingResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judge_id', models.CharField(help_text='Judge ID', max_length=255)),
                ('score', models.IntegerField(help_text='Score')),
                ('award', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='judge_app.Award')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('response_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('school', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=50)),
                ('grade_level', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=10)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='judge_app.Project')),
            ],
        ),
        migrations.AddField(
            model_name='judgingresult',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='judge_app.Project'),
        ),
        migrations.AddField(
            model_name='awardwinner',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='judge_app.Project'),
        ),
        migrations.AddField(
            model_name='award',
            name='projects',
            field=models.ManyToManyField(blank=True, related_name='awards', to='judge_app.Project'),
        ),
        migrations.AddField(
            model_name='award',
            name='winners',
            field=models.ManyToManyField(blank=True, related_name='winners', through='judge_app.AwardWinner', to='judge_app.Project'),
        ),
    ]
