# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-11 16:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('judge_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='judgingresult',
            name='award',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='judge_app.Award'),
            preserve_default=False,
        ),
    ]
