# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-11 16:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge_app', '0002_judgingresult_award'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='awardwinner',
            name='award',
        ),
        migrations.AlterField(
            model_name='award',
            name='winners',
            field=models.ManyToManyField(blank=True, related_name='winners', to='judge_app.AwardWinner'),
        ),
    ]
