# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-16 19:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge_app', '0003_auto_20160216_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='award',
            name='number_of_winners',
            field=models.IntegerField(blank=True, default=3, null=True),
        ),
    ]
