# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-11 16:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('judge_app', '0003_auto_20160211_1612'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='award',
            name='judge_results',
        ),
        migrations.RemoveField(
            model_name='award',
            name='winners',
        ),
    ]
