# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-11 17:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge_app', '0004_auto_20160211_1641'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='awardwinner',
            name='project',
        ),
        migrations.AlterField(
            model_name='award',
            name='grade_range',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.DeleteModel(
            name='AwardWinner',
        ),
    ]
