# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-11 17:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge_app', '0005_auto_20160211_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
