# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-18 09:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge_app', '0006_auto_20160216_1916'),
    ]

    operations = [
        migrations.AddField(
            model_name='award',
            name='number_of_judges',
            field=models.IntegerField(default=3),
        ),
    ]
