# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-11 19:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge_app', '0006_auto_20160211_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='award',
            name='project',
            field=models.ManyToManyField(to='judge_app.Project'),
        ),
        migrations.AlterField(
            model_name='judgingresult',
            name='judge_id',
            field=models.CharField(help_text='Judge ID', max_length=255),
        ),
        migrations.AlterField(
            model_name='judgingresult',
            name='score',
            field=models.IntegerField(help_text='Score'),
        ),
    ]
