# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-19 07:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('judge_app', '0007_award_number_of_judges'),
    ]

    operations = [
        migrations.CreateModel(
            name='Judge',
            fields=[
                ('judge_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('awards', models.ManyToManyField(blank=True, to='judge_app.Award')),
            ],
        ),
        migrations.AlterField(
            model_name='judgingresult',
            name='judge_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='judge_app.Judge'),
        ),
    ]
