# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-19 07:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('judge_app', '0008_auto_20160219_0731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='judgingresult',
            name='award',
            field=models.ForeignKey(help_text='The awards that this judge will be judging.', on_delete=django.db.models.deletion.CASCADE, to='judge_app.Award'),
        ),
    ]
