# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-13 07:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge_app', '0008_auto_20160211_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='award',
            name='projects',
            field=models.ManyToManyField(blank=True, related_name='awards', to='judge_app.Project'),
        ),
    ]
