# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-13 08:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge_app', '0009_auto_20160213_0747'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='award',
            name='id',
        ),
        migrations.AlterField(
            model_name='award',
            name='code',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
