# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-22 04:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge_app', '0009_auto_20160219_0733'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='judge',
            name='awards',
        ),
        migrations.AlterField(
            model_name='judgingresult',
            name='judge_id',
            field=models.CharField(help_text='Judge No.', max_length=255),
        ),
        migrations.DeleteModel(
            name='Judge',
        ),
    ]
