language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
env:
  - DJANGO="Django>=1.5,<1.6"
  - DJANGO="Django>=1.6,<1.7"
  - DJANGO="Django>=1.7,<1.8"
  - DJANGO="Django>=1.8,<1.9"
  - DJANGO="Django>=1.9,<1.10"
  - DJANGO="https://github.com/django/django/archive/master.tar.gz"
install:
  - pip install -q $DJANGO --use-mirrors
  - pip install -e git+https://github.com/kennethreitz/tablib.git#egg=tablib
  - pip install -r requirements/base.txt --use-mirrors
script:
  - python -Wall tests/manage.py test core --settings=
matrix:
  exclude:
    - python: "3.3"
      env: DJANGO="Django>=1.9,<1.10"
    - python: "3.3"
      env: DJANGO="https://github.com/django/django/archive/master.tar.gz"
  allow_failures:
    - env: DJANGO="https://github.com/django/django/archive/master.tar.gz"
